title: The Database 4 Everything
remote_theme: NadimGhaznavi/minimo

permalink: pretty

search_enabled: true
auto_page_title: true

sidebar:
  - Reports

plugins:
  - jekyll-relative-links
relative_link:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

  
minimo:
  skin: dark
