[tool.poetry]
name = "db4e"
version = "0.48.2"
license = "GPL-3.0-or-later"
description = "A unified Monero (XMR) mining dashboard for deployment, operations, and real-time analytics."
authors = ["Nadim-Daniel Ghaznavi <nghaznavi@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/NadimGhaznavi/Db4E"
repository = "https://github.com/NadimGhaznavi/Db4E"
keywords = ["monero", "mining", "textual", "dashboard", "analytics"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Topic :: System :: Monitoring",
]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"

# Core runtime dependencies
aiofiles = "^25.1.0"
fastapi = "^0.119.0"
httpx = "^0.28.1"
loguru = "^0.7.3"
myloginpath = "^0.0.4"
orjson = "^3.10.15"
psutil = "^7.0.0"
pydantic = "^2.12.2"
pystemd = "^0.15.3"
pytest-asyncio = "^1.2.0"
PyYAML = "^6.0.2"
requests = "^2.32.3"
rich = "^14.0.0"
sphinxcontrib-applehelp = "^2.0.0"
sphinxcontrib-devhelp = "^2.0.0"
sphinxcontrib-htmlhelp = "^2.0.0"
sphinxcontrib-jsmath = "^1.0.1"
sphinxcontrib-qthelp = "^2.0.0"
sphinxcontrib-serializinghtml = "^2.0.0"
sqlite-utils = "^3.35"
textual = {extras = ["syntax"], version = "^8.2.0"}
textual-dev = "^1.7.0"
textual-plot = "^0.10.1"
tomli_w = "^1.2.0"
uvicorn = "^0.37.0"
zstandard = "^0.23.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-mock = "^3.14.1"

[tool.poetry.scripts]
db4e = "db4e.Db4EClient:main"
db4e-server = "db4e.Db4EServer:main"

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
