# db4e/Constants/DForm.py
#
#    Database 4 Everything
#    Author: Nadim-Daniel Ghaznavi
#    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
#    GitHub: https://github.com/NadimGhaznavi/db4e
#    License: GPL 3.0


from typing import Final


class DForm:
    BLOCKCHAIN_DIR_LABEL: Final[str] = "blockchain_dir_label"
    BUTTON_ROW: Final[str] = "button_row"
    CHAIN_RADIO_SET: Final[str] = "chain_radio_set"
    CONFIG_FILE_LABEL: Final[str] = "config_file_label"
    CONFIG_LABEL: Final[str] = "config_label"
    FORM_0: Final[str] = "form_0"
    FORM_1: Final[str] = "form_1"
    FORM_2: Final[str] = "form_2"
    FORM_3: Final[str] = "form_3"
    FORM_4: Final[str] = "form_4"
    FORM_5: Final[str] = "form_5"
    FORM_6: Final[str] = "form_6"
    FORM_7: Final[str] = "form_7"
    FORM_8: Final[str] = "form_8"
    FORM_16: Final[str] = "form_16"
    FORM_DATA: Final[str] = "form_data"
    FORM_BOX: Final[str] = "form_box"
    FORM_FIELD: Final[str] = "form_field"
    HASHRATE_LABEL: Final[str] = "hashrate_label"
    HEALTH_LABEL: Final[str] = "health_label"
    INFO_MSG: Final[str] = "info_msg"
    INTRO: Final[str] = "form_intro"
    INPUT_7: Final[str] = "form_input_7"
    INPUT_15: Final[str] = "form_input_15"
    INPUT_30: Final[str] = "form_input_30"
    INPUT_40: Final[str] = "form_input_40"
    INPUT_70: Final[str] = "form_input_70"
    INSTANCE_INPUT: Final[str] = "instance_input"
    INSTANCE_LABEL: Final[str] = "instance_label"
    IP_ADDR_INPUT: Final[str] = "ip_addr_input"
    IP_ADDR_LABEL: Final[str] = "ip_addr_label"
    IN_PEERS_INPUT: Final[str] = "in_peers_input"
    IN_PEERS_LABEL: Final[str] = "in_peers_label"
    FORM_LABEL: Final[str] = "form_label"
    FORM_LABEL_15: Final[str] = "form_label_15"
    FORM_LABEL_20: Final[str] = "form_label_20"
    FORM_LABEL_25: Final[str] = "form_label_25"
    GROUP_NAME_LABEL: Final[str] = "group_name_label"
    HEADER: Final[str] = "header"
    HEALTH_BOX: Final[str] = "health_box"
    INSTALL_DIR_LABEL: Final[str] = "install_dir_label"
    LOG_LEVEL_INPUT: Final[str] = "log_level_input"
    LOG_LEVEL_LABEL: Final[str] = "log_level_label"
    LOG_WIDGET: Final[str] = "log_widget"
    LOGROTATE_CONFIG_LABEL: Final[str] = "logrotate_config_label"
    MAX_LOG_FILES_INPUT: Final[str] = "max_log_files_input"
    MAX_LOG_SIZE_INPUT: Final[str] = "max_log_size_input"
    NUM_THREADS_INPUT: Final[str] = "num_threads_input"
    OUT_PEERS_INPUT: Final[str] = "out_peers_input"
    OUT_PEERS_LABEL: Final[str] = "out_peers_label"
    P2P_BIND_PORT_INPUT: Final[str] = "MAX_LOG_SIZE_INPUT"
    P2P_PORT_INPUT: Final[str] = "p2p_port_input"
    P2P_PORT_LABEL: Final[str] = "p2p_port_label"
    PANE_BOX: Final[str] = "pane_box"
    PARENT_LABEL: Final[str] = "parent_label"
    PRIORITY_NODE_1_INPUT: Final[str] = "priority_node_1_input"
    PRIORITY_NODE_2_INPUT: Final[str] = "priority_node_2_input"
    PRIORITY_PORT_1_INPUT: Final[str] = "priority_port_1_input"
    PRIORITY_PORT_2_INPUT: Final[str] = "priority_port_2_input"
    RADIO_BUTTON_TYPE: Final[str] = "radio_button_type"
    RADIO_SET: Final[str] = "radio_set"
    RPC_BIND_PORT_INPUT: Final[str] = "rpc_bind_port_input"
    SELECT_BOX: Final[str] = "select_box"
    SHARES_FOUND_PLOT: Final[str] = "shares_found_plot"
    STATIC: Final[str] = "static_content"
    STRATUM_PORT_INPUT: Final[str] = "stratum_port_input"
    STRATUM_PORT_LABEL: Final[str] = "stratum_port_label"
    TIMES: Final[str] = "times"
    UPTIME_LABEL: Final[str] = "uptime_label"
    USER_NAME_LABEL: Final[str] = "user_name_label"
    USER_WALLET_INPUT: Final[str] = "user_wallet_input"
    VENDOR_DIR_INPUT: Final[str] = "vendor_dir_input"
    VENDOR_DIR_LABEL: Final[str] = "vendor_dir_label"
    ZMQ_PUB_PORT_INPUT: Final[str] = "zmq_pub_port_input"
    ZMQ_RPC_PORT_INPUT: Final[str] = "zmq_rpc_port_input"
