# db4e/Constants/DHealth.py
#
#    Database 4 Everything
#    Author: Nadim-Daniel Ghaznavi
#    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
#    GitHub: https://github.com/NadimGhaznavi/db4e
#    Website: https://db4e.osoyalce.com/
#    License: GPL 3.0


from db4e.constants.DField import DField as FIELD
from db4e.constants.DLabel import DLabel as LABEL


class DCategory:
    BLOCKCHAIN_DIR = FIELD.BLOCKCHAIN_DIR
    BLOCKCHAIN_SIZE_GB = FIELD.BLOCKCHAIN_SIZE_GB
    ENABLED = FIELD.ENABLED
    PRIMARY_SERVER = FIELD.PRIMARY_SERVER
    RPC_BIND_PORT = FIELD.RPC_BIND_PORT
    RUNNING = FIELD.RUNNING
    STRATUM_PORT = FIELD.STRATUM_PORT
    UPSTREAM = FIELD.UPSTREAM
    VENDOR_DIR = FIELD.VENDOR_DIR
    ZMQ_PUB_PORT = FIELD.ZMQ_PUB_PORT


CATEGORY_LABEL_MAP = {
    FIELD.BLOCKCHAIN_DIR: LABEL.BLOCKCHAIN_DIR,
    FIELD.ENABLED: LABEL.ENABLED,
    FIELD.PRIMARY_SERVER: LABEL.PRIMARY_SERVER,
    FIELD.RPC_BIND_PORT: LABEL.RPC_BIND_PORT,
    FIELD.RUNNING: LABEL.RUNNING,
    FIELD.STRATUM_PORT: LABEL.STRATUM_PORT,
    FIELD.UPSTREAM: LABEL.UPSTREAM,
    FIELD.VENDOR_DIR: LABEL.VENDOR_DIR,
    FIELD.ZMQ_PUB_PORT: LABEL.ZMQ_PUB_PORT,
}
