# db4e/Constants/DLabel.py
#
#    Database 4 Everything
#    Author: Nadim-Daniel Ghaznavi
#    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
#    GitHub: https://github.com/NadimGhaznavi/db4e
#    License: GPL 3.0


from db4e.util.ConstGroup import ConstGroup


class DLabel(ConstGroup):
    ACTIVE_MINERS: str = "Active Miners"
    ALL_TIME: str = "All Available"
    APPLY: str = "Apply"
    ANY_IP: str = "Listen on IP"
    API: str = "API"
    BLOCKCHAIN: str = "Blockchain"
    BLOCKCHAIN_DIR: str = "Blockchain Directory"
    BLOCKS: str = "Blocks"
    CHAIN: str = "Chain"
    CHAIN_STATS: str = "Chain Stats"
    CONFIG: str = "Configuration"
    CONFIG_FILE: str = "Configuration File"
    CURRENT: str = "Current"
    DAYS: str = "Days"
    DB4E: str = "Db4E Core"
    DB4E_LONG: str = "Database 4 Everything"
    DB4E_GROUP: str = "Db4E Group"
    DB4E_USER: str = "Db4E User"
    DETAILS: str = "Details"
    DEPLOYMENTS: str = "Deployments"
    DONATIONS: str = "Donations"
    DONATIONS_WALLET: str = "Donations Wallet"
    ENABLED: str = "Enabled"
    ELEMENT_TYPE: str = "Component"
    ENABLED_FLAG: str = "Enabled flag"
    END: str = "End"
    ERROR: str = "Error"
    EVENT: str = "Event"
    GROUP: str = "Group"
    H_PER_S: str = "H/s"
    HASHRATES: str = "Hashrates"
    HEALTH: str = "Health Checks"
    HEALTH_MSGS: str = "Health Checks"
    IN_PEERS: str = "Inbound max peers"
    INITIAL_SETUP: str = "Initial Setup"
    INSTALL_DIR: str = "Install Directory"
    INSTANCE: str = "Instance"
    IP_ADDR: str = "Hostname/IP Address"
    LOCAL_TIMESTAMP: str = "Localtime Timestamp"
    LOCAL_SOFTWARE_SYSTEM: str = "Local Software System"
    LOG: str = "Log"
    LOG_FILE: str = "Log File"
    LOG_LEVEL: str = "Log level"
    LOG_ROTATE_CONFIG: str = "logrotate configuration"
    LOG_VIEWER: str = "Log Viewer"
    MACHINE: str = "Host"
    MAIN_CHAIN: str = "Main"
    MAIN_CHAIN_LONG: str = "Main Chain"
    MINI_CHAIN: str = "Mini"
    MINI_CHAIN_LONG: str = "Mini Sidechain"
    MAX_LOG_FILES: str = "Max log files number"
    MAX_LOG_SIZE: str = "Max log file size"
    MESSAGE: str = "Message"
    METRICS: str = "Metrics"
    MONEROD: str = "Monero Daemon"
    MONEROD_REMOTE: str = "Remote Monero Daemon"
    MONEROD_REMOTE_SHORT: str = "Remote Monero"
    MONEROD_SHORT: str = "Monero"
    MONTH_1: str = "One Month"
    MONTHS_3: str = "Three Months"
    MONTHS_6: str = "Six Months"
    NANO_CHAIN: str = "Nano"
    NANO_CHAIN_LONG: str = "Nano Sidechain"
    NUM_THREADS: str = "Number of threads"
    OBJECT_ID: str = "Object ID"
    OPERATION: str = "Operation"
    OPS_MGR: str = "Ops Manager"
    OUT_PEERS: str = "Outbound max peers"
    P2P_PORT: str = "P2P Port"
    P2P_BIND_PORT: str = "P2P bind port"
    P2POOL: str = "P2Pool Daemon"
    P2POOL_INTERNAL: str = "Internal P2Pool Daemon"
    P2POOL_INTERNAL_SHORT: str = "Internal P2Pool"
    P2POOL_REMOTE: str = "Remote P2Pool Daemon"
    P2POOL_REMOTE_SHORT: str = "Remote P2Pool"
    P2POOL_SHORT: str = "P2Pool"
    P2POOL_WATCHER: str = "P2Pool Watcher"
    PARENT: str = "Parent"
    PARENT_ID: str = "Parent ID"
    PARENT_REMOTE: str = "Parent Remote"
    PLOT: str = "Plot"
    PRIMARY_SERVER: str = "Primary Server"
    PRIMARY_REMOTE: str = "Primary Remote"
    PRIORITY_NODE_1: str = "Priority node 1"
    PRIORITY_NODE_2: str = "Priority node 2"
    PRIORITY_PORT_1: str = "Priority port 1"
    PRIORITY_PORT_2: str = "Priority port 2"
    REMOTE: str = "Remote"
    RESULTS: str = "Results"
    RPC_BIND_PORT: str = "RPC bind port"
    RUNTIME_LOG: str = "Runtime Log"
    SHARES: str = "Shares"
    SHOW_TIME_STATS: str = "Show Time Stats"
    SOFTWARE_SYSTEM: str = "Software System"
    STATUS: str = "Status"
    STARTUP_SCRIPT: str = "Startup script"
    STATS_MOD: str = "API stats_mod"
    STDIN_PATH: str = "Standard Input FIFO"
    STRATUM_PORT: str = "Stratum port"
    TIMESTAMP: str = "Timestamp"
    TOTAL: str = "Total"
    TUI_LOG: str = "Console Log"
    TYPE: str = "Type"
    UPSTREAM_MONERO: str = "Upstream Monero"
    UPSTREAM_P2POOL: str = "Upstream P2Pool"
    USER: str = "User"
    USER_WALLET: str = "Monero user wallet"
    VENDOR_DIR: str = "Deployment directory"
    VERSION: str = "Version"
    WEEK_1: str = "One Week"
    WEEKS_2: str = "Two Weeks"
    WELCOME: str = "Welcome"
    WALLET: str = "Monero Wallet"
    WINDOWS: str = "Windows"
    XMRIG: str = "XMRig Miner"
    XMRIG_SHORT: str = "XMRig"
    XMRIG_REMOTE: str = "Remote XMRig Miner"
    XMRIG_REMOTE_SHORT: str = "Remote XMRig"
    XMRIG_SHORT: str = "XMRig"
    ZMQ_PUB_PORT: str = "ZMQ pub port"
    ZMQ_RPC_PORT: str = "ZMQ RPC port"
