"""
db4e/Constants/Labels.py

    Database 4 Everything
    Author: Nadim-Daniel Ghaznavi 
    Copyright: (c) 2024-2025 Nadim-Daniel Ghaznavi
    GitHub: https://github.com/NadimGhaznavi/db4e
    License: GPL 3.0
"""

from enum import StrEnum



class DLabel(StrEnum):
    ABORT = "Abort"
    ACTIVE_MINERS = "Active Miners"
    ANY_IP = "Listen on IP"
    ANALYTICS = "Mining Analytics"
    API = "API"
    BLOCKS_FOUND = "Blocks Found"
    CHAIN = "Chain"
    CHAIN_STATS = "Chain Stats"
    CONFIG = "Configuration"
    CONFIG_FILE = "Configuration File"
    DATA_DIR = "Blockchain Directory"
    DB4E = "Db4E Core"
    DB4E_LONG = "Database 4 Everything"
    DB4E_GROUP = "Db4E Group"
    DB4E_USER = "Db4E User"
    DELETE = "Delete"
    DEPLOYMENTS = "Deployments"
    DISABLE = "Disable"
    DONATIONS = "Donations"
    DONATIONS_WALLET = "Donations Wallet"
    ENABLE = "Enable"
    GROUP = "Group"
    HASHRATES = "Hashrates"
    HEALTH = "Health Checks"
    HEALTH_MSGS = "Health Checks"
    IN_PEERS = "Incoming Peer Connections"
    INITIAL_SETUP = "Initial Setup"
    INSTALL_DIR = "Install Directory"
    INSTANCE = "Instance"
    IP_ADDR = "Hostname/IP Address"
    LOCAL_SOFTWARE_SYSTEM = "Local Software System"
    LOG = "Log"
    LOG_LEVEL = "Log Level"
    LOG_FILE = "Log File"
    LOG_VIEWER = "Log Viewer"
    MACHINE = "Host"
    MAIN_CHAIN = "Main Chain"
    MINI_CHAIN = "Mini Chain"
    MAX_LOG_FILES = "Maximum Number of Log Files"
    MAX_LOG_SIZE = "Maximum Log File Size"
    METRICS = "Metrics"
    MONEROD = "Monero Daemon"
    MONEROD_REMOTE = "Remote Monero Daemon"
    MONEROD_SHORT = "Monero"
    NANO_CHAIN = "Nano Chain"
    NEW = "New"
    NUM_THREADS = "Number of Threads"
    OBJECT_ID = "Object ID"
    OPS_MGR = "Ops Manager"
    OUT_PEERS = "Outgoing Peer Connections"
    P2P_BIND_PORT = "P2P Bind Port"
    P2POOL = "P2Pool Daemon"
    P2POOL_REMOTE = "Remote P2Pool Daemon"
    P2POOL_SHORT = "P2Pool"
    PARENT = "Parent"
    PARENT_ID = "Parent ID"
    PLOT = "Plot"
    PRIMARY_SERVER = "Primary Server"
    PRIORITY_NODE_1 = "Priority Node 1"
    PRIORITY_NODE_2 = "Priority Node 2"
    PRIORITY_PORT_1 = "Priority Port 1"
    PRIORITY_PORT_2 = "Priority Port 2"
    PROCEED = "Proceed"
    REMOTE = "Remote"
    RESULTS = "Results"
    RPC_BIND_PORT = "RPC Bind Port"
    SHOW_TIME_STATS = "Show Time Stats"
    SOFTWARE_SYSTEM = "Software System"
    START = "Start"
    STARTUP_SCRIPT = "Startup Script"
    STDIN = "Standard Input"
    STOP = "Stop"
    STRATUM_PORT = "Stratum Port"
    TUI_LOG = "Console Log"
    UPDATE = "Update"
    USER = "User"
    USER_WALLET = "Monero User Wallet"
    VENDOR_DIR = "Deployment Directory"
    VERSION = "Version"
    WELCOME = "Welcome"
    WALLET = "Monero Wallet"
    XMRIG = "XMRig Miner"
    XMRIG_SHORT = "XMRig"
    ZMQ_PUB_PORT = "ZMQ Pub Port"
    ZMQ_RPC_PORT = "ZMQ RPC Port"

